improve CI

diff --git a/.github/workflows/docker-image-terminal.yml b/.github/workflows/docker-image-terminal.yml
--- a/.github/workflows/docker-image-terminal.yml
+++ b/.github/workflows/docker-image-terminal.yml
@@ -19,8 +19,13 @@ on:
         default: "latest"
         type: string
 
+env:
+  IMAGE_NAME: terminal
+  DOCKERFILE_DIR: terminal
+
 jobs:
   build:
+    name: Build image
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -30,6 +35,21 @@ jobs:
         uses: actions/checkout@v4
         with:
           submodules: recursive
+
+      - name: Extract version from Dockerfile
+        id: version
+        run: |
+          LINE=$(grep -A1 '# @version' docker/${DOCKERFILE_DIR}/Dockerfile | tail -n1)
+          echo "Matched line: $LINE"
+
+          VERSION=$(echo "$LINE" | sed -E 's/^FROM [^:]+:([^ ]+).*/\1/')
+          if [ -z "$VERSION" ]; then
+            echo "Could not extract version from Dockerfile"
+            exit 1
+          fi
+
+          echo "base_version=$VERSION" >> $GITHUB_OUTPUT
+          echo "Found version: $VERSION"
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
@@ -44,23 +64,36 @@ jobs:
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Compute Docker tags
+        id: docker_tags
+        run: |
+          BASE_VERSION="${{ steps.version.outputs.base_version }}"
+          INPUT_TAG="${{ inputs.tag }}"
+
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" && "${INPUT_TAG}" != "latest" ]]; then
+            TAGS="type=raw,value=${INPUT_TAG}"
+          else
+            TAGS="type=raw,value=latest\ntype=raw,value=${BASE_VERSION}"
+          fi
+
+          echo 'computed_tags<<EOF' >> $GITHUB_OUTPUT
+          echo -e "$TAGS" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+          echo "Computed tags: $TAGS"
+
       - name: Docker meta
         id: meta
-        if: steps.docker.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
         uses: docker/metadata-action@v5
         with:
-          tags: |
-            type=ref,event=branch
-            type=raw,value=latest
-            type=raw,value=${{ inputs.tag }}
-          images: ghcr.io/detavern/terminal
+          images: ghcr.io/detavern/${{ env.IMAGE_NAME }}
+          tags: ${{ steps.docker_tags.outputs.computed_tags }}
 
       - name: Build and push Docker images
-        if: steps.docker.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6
         with:
-          platforms: linux/amd64,linux/arm64,linux/arm
-          context: ./docker/terminal
+          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
+          context: ./docker/${{ env.DOCKERFILE_DIR }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           push: true
